"use client"

import { useEffect, useRef, useState } from "react"

export function Features() {
  const [isVisible, setIsVisible] = useState(false)
  const sectionRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true)
        }
      },
      { threshold: 0.1 }
    )

    if (sectionRef.current) {
      observer.observe(sectionRef.current)
    }

    return () => observer.disconnect()
  }, [])

  const features = [
    {
      number: "01",
      title: "Formation Detection",
      description:
        "Identify tactical setups in real-time. AI-powered clarity tracks transitions between offensive and defensive formations in the full 90 minutes.",
    },
    {
      number: "02",
      title: "AI Tactical Report",
      description:
        "Get an AI-formatted, readable report. High-pressuring offensive efficiency, defensive patterns, and weakness analysis generated by LLM.",
    },
    {
      number: "03",
      title: "Possession Analysis",
      description:
        "Visualize territorial dominance zones. Spot dangerous space patterns, and AI-generated pass/offensive line analysis covering all key heatmaps.",
    },
  ]

  return (
    <section 
      ref={sectionRef}
      id="features" 
      className="border-b border-border/40 bg-background py-24 md:py-32"
    >
      <div className="container mx-auto px-4">
        <div className={`mx-auto mb-20 max-w-5xl text-center transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
          <p className="mb-4 text-xs font-semibold uppercase tracking-[0.25em] text-primary">Core Features</p>
          <h2 className="mb-6 text-editorial-lg font-[family-name:var(--font-display)] font-bold tracking-tight text-foreground">
            Professional Intelligence Tools
          </h2>
          <p className="text-body-editorial text-muted-foreground max-w-3xl mx-auto">
            Cutting-edge AI analysis designed to transform how you understand the game
          </p>
        </div>

        <div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3">
          {features.map((feature, index) => (
            <div
              key={index}
              className={`group rounded-3xl border-2 border-border/40 bg-card/30 p-10 transition-all duration-700 hover:border-primary/60 hover:bg-card/60 hover:shadow-2xl hover:shadow-primary/5 hover:-translate-y-2 ${
                isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'
              }`}
              style={{ transitionDelay: `${index * 150}ms` }}
            >
              <div className="mb-8 inline-flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 transition-all duration-300 group-hover:from-primary/30 group-hover:to-primary/10 group-hover:scale-110">
                <span className="text-4xl font-bold font-[family-name:var(--font-display)] text-primary">{feature.number}</span>
              </div>
              <h3 className="mb-5 text-2xl font-bold text-foreground tracking-tight">{feature.title}</h3>
              <p className="text-base leading-relaxed text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
